command_timeout = 4_000

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "

[[battery.display]]
threshold = 20

[cmd_duration]
show_milliseconds = true
show_notifications = true
min_time = 2_000
min_time_to_notify = 15_000
format = '[$duration](bold yellow)'

[nodejs]
symbol = "â¬¢ "

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
style = "bold dimmed white"
disabled = true

[git_status]
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
